name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Publish
      run: dotnet publish --no-restore -r ubuntu.16.04-x64 -c Release
    #- name: copy file via ssh key
    #  uses: appleboy/scp-action@master
    #  with:
    #    host: ${{ secrets.HOST }}
    #    username: ${{ secrets.USERNAME }}
    #    port: ${{ secrets.PORT }}
    #    key: ${{ secrets.KEY }}
    #    passphrase: ${{ secrets.PASSPHRASE }}
    #    source: "tests/a.txt,tests/b.txt"
    #    target: "test"
