name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Publish
      run: dotnet publish -r ubuntu.16.04-x64 -c Release --self-contained true --nologo
    - name: Deploy (SCP)
      # only deploy from merged master
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./LennyBOTv3/bin/Release/net6.0/ubuntu.16.04-x64/publish/*"
        target: "/home/seky16/LennyBOTv3"
        strip_components: 6
